version: '3.9'

services:
  muer:
    container_name: muer
    image: muerorg/muer:latest
    hostname: muer
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    read_only: false
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000
    ports:
      - 3000:3000
    # volumes:
    #   - /etc/TZ:/etc/timezone:ro
    #   - /etc/localtime:/etc/localtime:ro